service: team-1-etl

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iam:  
    role: arn:aws:iam::883232869702:role/data-lambda-role

plugins:
  - serverless-iam-roles-per-function

custom:
  enterprise:
    collectLambdaLogs: false


package:
  include: 
    - src/**
    - handler.py
  exclude:
    - "*"
    - "*/**" 
  individually: true
  excludeDevDependencies: false

functions:
  etl:
    handler: handler.handel
    timeout: 300
    layers:
      - arn:aws:lambda:eu-west-1:883232869702:layer:ELT-Lambda:2
    events:
      - s3:
          bucket: gen-x1-team-1-data-in
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .csv

resources:
  Resources:
    IamRoleCustomResourcesLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        PermissionsBoundary: arn:aws:iam::883232869702:policy/ScopePermissions
        AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service:
                      - lambda.amazonaws.com
                  Action: sts:AssumeRole
    